### ISSUE TITLE
PCC Vivace

### ISSUE THREAD

**Issue by bcronje** [PCCproject/PCC-Uspace#1]
Is the Vivace code in the `master` branch, or should I work from the `NSDI-2018` branch to review Vivace utility implementation?

**Comment by nathanhjay** [comment]
The PCC-Vivace code is in the master branch. The ```CalculateUtility``` function in https://github.com/PCCproject/PCC-Uspace/blob/master/src/pcc/pcc_monitor_interval_queue.cpp is where you can see the exact utility computation. I'm working to move this to a separate file so it's easier for others to view, understand and modify.

**Comment by bcronje** [comment]
Thank you @nathanhjay
