### ISSUE TITLE
unable to access http://www.ttmeng.net/pubs/vivace_proof.pdf

### ISSUE THREAD

**Issue by MasterXS** [PCCproject/PCC-Uspace#25]
is there any new url for vivace_proof.pdf downloading? thanks!

**Comment by brighten** [comment]
Hi, thanks for your interest.  For now, contact me via email at pbg at illinois dot edu .

**Comment by xinstriving** [comment]
> Hi, thanks for your interest. For now, contact me via email at pbg at illinois dot edu .
I am also very interested in the certificate and have already sent you an email. Could you please send me a certificate? Thank you very much!
