### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dfshan** [PCCproject/PCC-Uspace#4]
When I run the command `sunifdef -r -UQUIC_PORT -UQUIC_PORT_LOCAL ./pcc/\\*" in directory "src", I get the following error:
```
sunifdef: abend 0x08280: No such file or directory as "./pcc/*"
```
I have no idea why I get this error...

sunidef version 3.1.3 for Unix
OS: CentOS 7.5.1804 with kernel version 4.16.13

**Comment by nathanhjay** [comment]
Hmm. There could be a relative path problem. Can you try giving sunifdef the absolute path to the src/pcc directory?

**Comment by dfshan** [comment]
I have given the absolute path to the sunidef, but there is till error as follows:
```
sunifdef: abend 0x08280: No such file or directory as "/home/dfshan/PCC-Uspace/src/pcc/*"
```
Which OS do you use in your experiments?
And can I use the source code in the branch NSDI-2018 instead?

**Comment by nathanhjay** [comment]
We used Ubuntu 14.0.4. You can look at the NSDI-2018 code and use it if you wish, but you'll find that the organization is more difficult to follow. In general, if you'd like to be able to keep up-to-date, it would be good to use the newer version. If you need something working in the short term though, the NSDI-2018 branch should be fine.

**Comment by dfshan** [comment]
Thank you very much. The code at the NSDI-2018 branch can be successfully compiled in my machine.
But when I run the program, I find that the **CPU utilization is so high** at the client side that **the network can not be fully utilized**.

Specifically, in a 10Mbps network, Vivace can only achieve a throughput of 1.2Mbps.

I don't know whether I did something wrong. What's the minimum system requirements to run this program?

Our machine has a 4-core Intel Core i3-3240 3.4 GHz CPU, a 4 GB memory, a 500 GB hard disk. Running CentOS 7.5 with Linux kernel 4.17.

In our testbed, 2 hosts are connected to another host emulating a router. The router has 50KB buffer and the speed is 10Mbps. The RTT is 10ms.


![image](https://user-images.githubusercontent.com/4088802/42486274-bcd0ba94-842d-11e8-8929-d4f214b8f5c9.png)

**Comment by nathanhjay** [comment]
The underlying UDT library uses a single core to 100% utilization for exact packet pacing, but that shouldn't be keeping the throughput so low. Usually we can get around 1Gbps with a modern desktop processor, and we've been able to get about 270Mbps even on low-end or old hardware.

That Linux kernel version should be fine, but I haven't done any testing with CentOS.

Is there high random loss on the emulated link? Can you try iperf and let me know how TCP performs?

**Comment by dfshan** [comment]
The link has no random loss. With iperf, TCP (CUBIC) can achieve 100% throughput (i.e., 10Mbps). Maybe I should try Ubuntu.

**Comment by nathanhjay** [comment]
I think the initial problem with compiler errors was fixed, so I'll mark this closed.

**Comment by amirmirzaeinia** [comment]
Hello, I have the same issue on MacOS Mojave, 
sunifdef: abend 0x08280: No such file or directory as "/abs_path/PCC-Uspace/src/pcc/*".  Any recent update?Thank you

**Comment by dfshan** [comment]
Run the following command in the directory `src` does not raise any errors:
``` bash
sunifdef -r -UQUIC_PORT -UQUIC_PORT_LOCAL ./pcc/*
```

**Comment by hexi519** [comment]
> Hello, I have the same issue on MacOS Mojave,
> sunifdef: abend 0x08280: No such file or directory as "/abs_path/PCC-Uspace/src/pcc/*". Any recent update?Thank you

I got the same error and I have already in PCC-Uspace/src ,my branch is deep-learning and my OS is Ubuntu 16.04, any help?
